server:
  port: ${PORT:8090}

security:
  oauth2:
    client:
      client-id: auth_id
      client-secret: auth_secret
      resource:
        jwt:
          key-value: jwt_secret_key

spring:
  h2:
    console:
      enabled: true
      path: /h2-console