spring:
  application:
    name: api-gateway
server:
  port: ${PORT:8080}

zuul:
  routes:
    api-member:
      path: /api-member/**
      url: http://localhost:8081
    api-chat:
      path: /api-chat/**
      url: http://localhost:8082
