spring:
  application:
    name: api-gateway
server:
  port: ${PORT:8080}

zuul:
  routes:
    oauth:
      path: /oauth/**
      url: http://localhost:9090
    api-member:
      path: /api-member/**
      url: http://localhost:8081
    api-chat:
      path: /api-chat/**
      url: http://localhost:8082
  thread-pool:
    use-separate-thread-pools: true
    thread-pool-key-prefix: zuul-
  ribbon-isolation-strategy: thread
  sensitiveHeaders: Cookie,Set-Cookie

security:
  oauth2:
    resource:
      jwt:
        key-value: msc


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
    api-member:
      excution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
  threadpool:
    zuul-api-member:
      coreSize: 30
      maximumSize: 100
      allowMaximumSizeToDivergeFromCoreSize: true
    zuul-api-chat:
      coreSize: 30
      maximumSize: 100
      allowMaximumSizeToDivergeFromCoreSize: true


api-member:
  ribbon:
    MaxAutoRetriesNextServer: 1
    ReadTimeOut: 3000
    ConnectTimeout: 1000
    MaxTotalConnections: 300
    MaxConnectionsPerHost: 100

api-chat:
  ribbon:
    MaxAutoRetriesNextServer: 1
    ReadTimeOut: 3000
    ConnectTimeout: 1000
    MaxTotalConnections: 300
    MaxConnectionsPerHost: 100