server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: ${JDBC_DATABASE_URL:jdbc:h2:tcp://localhost/~/talk}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: sa
#    password: password
#    url: ${JDBC_DATABASE_URL:jdbc:mysql://mysql-member:3306/member}


  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jpa:
          default_batch_fetch_size: 10
        jdbc:
          lob:
            non_contextual_creation: true
          id:
            new_generator_mappings: true

springdoc:
  pathsToMatch: /api/**
